language: python

python:
  - "3.8"
  - "3.9"

# Install dependencies.
install:
  - pip3 install -r requirements.txt

# Run tests.
script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
